# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .auto_deployer import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "auto-deploy",
  "mod": "index",
  "fqn": "pulumi_auto_deploy",
  "classes": {
   "auto-deploy:index:AutoDeployer": "AutoDeployer"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "auto-deploy",
  "token": "pulumi:providers:auto-deploy",
  "fqn": "pulumi_auto_deploy",
  "class": "Provider"
 }
]
"""
)
