# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['AutoDeployerArgs', 'AutoDeployer']

@pulumi.input_type
class AutoDeployerArgs:
    def __init__(__self__, *,
                 downstream: pulumi.Input[Sequence[Any]],
                 organization: pulumi.Input[str],
                 project: pulumi.Input[str],
                 stack: pulumi.Input[str]):
        """
        The set of arguments for constructing a AutoDeployer resource.
        """
        pulumi.set(__self__, "downstream", downstream)
        pulumi.set(__self__, "organization", organization)
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "stack", stack)

    @property
    @pulumi.getter
    def downstream(self) -> pulumi.Input[Sequence[Any]]:
        return pulumi.get(self, "downstream")

    @downstream.setter
    def downstream(self, value: pulumi.Input[Sequence[Any]]):
        pulumi.set(self, "downstream", value)

    @property
    @pulumi.getter
    def organization(self) -> pulumi.Input[str]:
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: pulumi.Input[str]):
        pulumi.set(self, "organization", value)

    @property
    @pulumi.getter
    def project(self) -> pulumi.Input[str]:
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[str]):
        pulumi.set(self, "project", value)

    @property
    @pulumi.getter
    def stack(self) -> pulumi.Input[str]:
        return pulumi.get(self, "stack")

    @stack.setter
    def stack(self, value: pulumi.Input[str]):
        pulumi.set(self, "stack", value)


class AutoDeployer(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 downstream: Optional[pulumi.Input[Sequence[Any]]] = None,
                 organization: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 stack: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a AutoDeployer resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AutoDeployerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AutoDeployer resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param AutoDeployerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AutoDeployerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 downstream: Optional[pulumi.Input[Sequence[Any]]] = None,
                 organization: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 stack: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AutoDeployerArgs.__new__(AutoDeployerArgs)

            if downstream is None and not opts.urn:
                raise TypeError("Missing required property 'downstream'")
            __props__.__dict__["downstream"] = downstream
            if organization is None and not opts.urn:
                raise TypeError("Missing required property 'organization'")
            __props__.__dict__["organization"] = organization
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            if stack is None and not opts.urn:
                raise TypeError("Missing required property 'stack'")
            __props__.__dict__["stack"] = stack
            __props__.__dict__["deployment_webhook_urls"] = None
        super(AutoDeployer, __self__).__init__(
            'auto-deploy:index:AutoDeployer',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter(name="deploymentWebhookURLs")
    def deployment_webhook_urls(self) -> pulumi.Output[Sequence[str]]:
        return pulumi.get(self, "deployment_webhook_urls")

    @property
    @pulumi.getter
    def organization(self) -> pulumi.Output[str]:
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter
    def project(self) -> pulumi.Output[str]:
        return pulumi.get(self, "project")

    @property
    @pulumi.getter
    def stack(self) -> pulumi.Output[str]:
        return pulumi.get(self, "stack")

