permissions: write-all
name: Export secrets to ESC
on: [ workflow_dispatch ]
jobs:
  export-to-esc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1256780
          private-key: ${{ secrets.EXPORT_SECRETS_PRIVATE_KEY }}
      - uses: pulumi/esc-export-secrets-action@9d6485759b6adff2538ae91f1b77cc96265c9dad # v1
        with:
          organization: pulumi
          org-environment: github-secrets/pulumi-auto-deploy
          exclude-secrets: EXPORT_SECRETS_PRIVATE_KEY
        env:
          GITHUB_SECRETS: ${{ toJSON(secrets) }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
