// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Automatically trigger downstream updates on dependent stacks via Pulumi Deployments.
 * AutoDeployer requires that stacks have Deployment Settings configured.
 */
export class AutoDeployer extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'auto-deploy:index:AutoDeployer';

    /**
     * Returns true if the given object is an instance of AutoDeployer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AutoDeployer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AutoDeployer.__pulumiType;
    }

    /**
     * A list of `AutoDeployer.DownstreamRef` indicating which stacks should
     * automatically be updated via Pulumi Deployments when this stack is successfully updated.
     */
    public readonly downstreamRefs!: pulumi.Output<string[]>;
    /**
     * A list of webhook URLs configured on this stack to trigger downstream deployments.
     */
    public /*out*/ readonly downstreamWebhooks!: pulumi.Output<string[]>;
    /**
     * The organization name for the AutoDeployer stack.
     */
    public readonly organization!: pulumi.Output<string>;
    /**
     * The project name for the AutoDeployer stack.
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * The output reference that can be passed to another AutoDeployer's downstreamRefs list
     * to configure depedent updates.
     */
    public /*out*/ readonly ref!: pulumi.Output<string>;
    /**
     * The stack name for this AutoDeployer.
     */
    public readonly stack!: pulumi.Output<string>;

    /**
     * Create a AutoDeployer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AutoDeployerArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.downstreamRefs === undefined) && !opts.urn) {
                throw new Error("Missing required property 'downstreamRefs'");
            }
            if ((!args || args.organization === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organization'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.stack === undefined) && !opts.urn) {
                throw new Error("Missing required property 'stack'");
            }
            resourceInputs["downstreamRefs"] = args ? args.downstreamRefs : undefined;
            resourceInputs["organization"] = args ? args.organization : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["stack"] = args ? args.stack : undefined;
            resourceInputs["downstreamWebhooks"] = undefined /*out*/;
            resourceInputs["ref"] = undefined /*out*/;
        } else {
            resourceInputs["downstreamRefs"] = undefined /*out*/;
            resourceInputs["downstreamWebhooks"] = undefined /*out*/;
            resourceInputs["organization"] = undefined /*out*/;
            resourceInputs["project"] = undefined /*out*/;
            resourceInputs["ref"] = undefined /*out*/;
            resourceInputs["stack"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AutoDeployer.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AutoDeployer resource.
 */
export interface AutoDeployerArgs {
    /**
     * A list of `AutoDeployer.DownstreamRef` indicating which stacks should
     * automatically be updated via Pulumi Deployments when this stack is successfully updated.
     */
    downstreamRefs: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The organization name for the AutoDeployer stack.
     */
    organization: pulumi.Input<string>;
    /**
     * The project name for the AutoDeployer stack.
     */
    project: pulumi.Input<string>;
    /**
     * The stack name for this AutoDeployer.
     */
    stack: pulumi.Input<string>;
}
